from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

from app.application.services.reference_service import ReferenceService
from app.infrastructure.db import models_sqlalchemy as models

from .test_reference_service import make_session_factory


def test_seed_defaults_removes_unreferenced_autogenerated_items_and_keeps_used_rows(
    tmp_path: Path,
) -> None:
    session_factory = make_session_factory(tmp_path / "reference_seed_sync.db")
    service = ReferenceService(session_factory=session_factory)

    seed_payload = {
        "antibiotic_groups": [{"code": "ABG-0001", "name": "Group A"}],
        "antibiotics": [{"code": "ABX-0001", "name": "Seed Abx", "group_code": "ABG-0001"}],
        "microorganisms": [{"code": "MIC-0001", "name": "Seed Micro", "taxon_group": "Group A"}],
        "ismp_abbreviations": [],
    }
    seed_file = tmp_path / "seed.json"
    seed_file.write_text(json.dumps(seed_payload, ensure_ascii=False), encoding="utf-8")

    with session_factory() as session:
        session.add(models.RefAntibioticGroup(code="ABG-0999", name="Obsolete Group"))
        stale_abx = models.RefAntibiotic(code="ABX-0999", name="Obsolete Abx")
        kept_abx = models.RefAntibiotic(code="ABX-0998", name="Referenced Abx")
        custom_abx = models.RefAntibiotic(code="CUSTOM-ABX", name="Custom Abx")
        stale_micro = models.RefMicroorganism(code="MIC-0999", name="Obsolete Micro", taxon_group="Group B")
        kept_micro = models.RefMicroorganism(code="MIC-0998", name="Referenced Micro", taxon_group="Group B")
        custom_micro = models.RefMicroorganism(code="CUSTOM-MIC", name="Custom Micro", taxon_group="Group B")
        user = models.User(login="admin", password_hash="hash", role="admin")
        patient = models.Patient(full_name="Тестовый Пациент")
        material_type = models.RefMaterialType(code="MT-1", name="Material")
        session.add_all(
            [
                stale_abx,
                kept_abx,
                custom_abx,
                stale_micro,
                kept_micro,
                custom_micro,
                user,
                patient,
                material_type,
            ]
        )
        session.flush()

        emr_case = models.EmrCase(
            patient_id=patient.id,
            hospital_case_no="CASE-1",
            created_by=user.id,
        )
        session.add(emr_case)
        session.flush()
        case_version = models.EmrCaseVersion(
            emr_case_id=emr_case.id,
            version_no=1,
            valid_from=datetime.now(UTC),
            is_current=True,
            entered_by=user.id,
        )
        session.add(case_version)
        session.flush()
        session.add(
            models.EmrAntibioticCourse(
                emr_case_version_id=case_version.id,
                antibiotic_id=kept_abx.id,
            )
        )

        lab_sample = models.LabSample(
            patient_id=patient.id,
            emr_case_id=emr_case.id,
            lab_no="LAB-1",
            material_type_id=material_type.id,
            created_by=user.id,
        )
        session.add(lab_sample)
        session.flush()
        session.add(
            models.LabMicrobeIsolation(
                lab_sample_id=lab_sample.id,
                microorganism_id=kept_micro.id,
            )
        )

    service.seed_defaults(seed_file)

    with session_factory() as session:
        antibiotic_codes = {
            str(item.code): str(item.name)
            for item in session.query(models.RefAntibiotic).order_by(models.RefAntibiotic.code).all()
        }
        microorganism_codes = {
            str(item.code): str(item.name)
            for item in session.query(models.RefMicroorganism).order_by(models.RefMicroorganism.code).all()
        }
        group_codes = {
            str(item.code): str(item.name)
            for item in session.query(models.RefAntibioticGroup).order_by(models.RefAntibioticGroup.code).all()
        }

    assert antibiotic_codes["ABX-0001"] == "Seed Abx"
    assert "ABX-0999" not in antibiotic_codes
    assert antibiotic_codes["ABX-0998"] == "Referenced Abx"
    assert antibiotic_codes["CUSTOM-ABX"] == "Custom Abx"

    assert microorganism_codes["MIC-0001"] == "Seed Micro"
    assert "MIC-0999" not in microorganism_codes
    assert microorganism_codes["MIC-0998"] == "Referenced Micro"
    assert microorganism_codes["CUSTOM-MIC"] == "Custom Micro"

    assert group_codes["ABG-0001"] == "Group A"
    assert "ABG-0999" not in group_codes
